repos:
  # Validation
  # uv run pre-commit run mmg-validation --all-files
  - repo: local
    hooks:
      - id: mmg-validation
        name: mmg validation
        entry: python .pre-commit-hooks/run-validation.py
        language: system
        files: \.base\.(md|ipynb)$
        exclude: ^examples/validation-examples/bad_.*$
        pass_filenames: true
        fail_fast: true
        verbose: true

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.14.0
  #   hooks:
  #     # Run the linter.
  #     - id: ruff-check
  #       args: [--fix]
  #     # Run the formatter.
  #     - id: ruff-format